### ISSUE TITLE
A few possible improvements for Linux (ebuild for Gentoo inside)

### ISSUE THREAD

**Issue by nonno-cicala** [mfeemster/fractorium#73] opened 2016-02-26 02:11 UTC
I wrote myself an ebuild today (the scripts used on Gentoo to install packages) and I noticed 3 things that could be cleaned in fractorium:

1. a `last.flame` file is created where I launch fractorium (I have 5 of them now, maybe it could go in `"${HOME}/.local/share/Fractorium"` (following [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html))? )
2. the binaries are rebuilt with `make install`, instead of just being installed
3. the libraries lack a SONAME (you could use something like LDFLAGS += -Wl,-soname,$(LIBRARY) )

If you think these are things that should be addressed I could open separate issues if you wish.

My ebuild is primitive because it has no options, unlike usual ebuilds, but it works here, so it could be better than nothing: [fractorium-9999.ebuild](https://github.com/mfeemster/fractorium/files/147557/fractorium-9999.ebuild.txt)

Is it possible to build fractorium without OpenCL or without Qt (without GUI)? These are options I could think to add later.

**Comment by mfeemster** [comment] 2016-02-26 06:41
@gambhiro Can you please answer questions 1-3? Thanks.

The answers for the last two questions are both no.

-OpenCL is intrinsic to it, you must build with it. Why would you not want to? Drivers are available for both major card manufacturers on all major platforms. It was one of the key aims of this project, so it can't be removed and wouldn't provide any value. Once it's built, nothing forces you to use OpenCL, you're welcome to use the CPU renderer if you don't have a supported card.

-Qt is for Fractorium only, so it's also impossible to remove. You cannot build the GUI without the GUI. However, if you only want command line support, you can build EmberRender, EmberAnimate and EmberGenome with Qt since they have no dependencies on it.

Granted, make all will try to build everything including Factorium, so it will look for Qt. Perhaps @gambhiro can provide a special make flag, something like --clionly to only build the command line programs?

Hope that helps.

**Comment by nonno-cicala** [comment] 2016-02-26 12:25
That helps, thanks.

Actually the last answer is more a yes than a no to me. Someone could just want an alternative to flam3 with OpenCL, and it makes more sense if it could drop the dependency on Qt5. Gentoo is about choices, I'll investigate the Makefile to find the targets needed to just build and install the command line support and I'll expose this choice to the users.

**Comment by mfeemster** [comment] 2016-02-26 14:41
Sounds good, I'll keep an eye out for your PR. I also fixed a typo above to read: withOUT Qt.

**Comment by gambhiro** [comment] 2016-02-28 16:48
`make install` only performs install for me on Ubuntu. Perhaps qmake generates different Makefiles on Gentoo? It is possible, but I don't how to help it. Same goes for the make flag for a cli only build... I have completely lost heart for trying to configure qmake for anything beyond getting it to build a `.deb`. It is such a confusing, underdocumented piece.

`cmake` could be the deliverance, but I haven't had the time to research it.

**Comment by mfeemster** [comment] 2016-02-28 17:22
Stop work on any of this, I am re-writing it.

**Comment by mfeemster** [comment] 2016-03-02 02:46
I have removed the symlinks file. Please update and rebuild. I am hoping it builds out of the box, but if not, please let me know of any remaining problems. Thanks.

**Comment by mfeemster** [comment] 2016-03-05 04:07
I would like to reopen this because I did not get to the problem with last.flame.

I was able to repro the problem and see what you mean. It's definitely not good.

I am unsure where to put it though. You mentioned some paths, but others have mentioned other paths. The problem is that with infinite configurability on Linux, nothing is really standard. For example, we search for palette paths here:

QDir::currentPath()
QDir::homePath()
QCoreApplication::applicationDirPath()
/usr/share/fractorium
/usr/local/share/fractorium

and also here in another place:

~/.fractorium
~/.config/fractorium

You have suggested here:

~/.local/share/Fractorium

As you can tell, this is merely a collection of where everyone thinks it ought to go. This is the farthest thing from a standard as one could get.

On Windows, it's simple: the same folder as the executable. The reason is that last.flame is meant to be an emergency backup of the last thing you rendered in case the program crashes. It's a last ditch attempt to rescue whatever you were doing if you didn't save it (which you should be doing regularly). Other than that, a user will never have a need to look at it.

Let me know your thoughts.

**Comment by gambhiro** [comment] 2016-03-07 18:30
The `/usr` paths are chosen by installing package, so we can configure them to be one of the possible places.

The `~/` dotfile paths are chosen by the application at runtime, so you can choose what folders to create where. `~/.config/fractorium` is a good spot.

The installing package never touches the user's home, the idea is that the application is supposed to copy its dotfiles to the folder it wants to find them on the first run.

**Comment by nonno-cicala** [comment] 2016-03-08 17:29
I agree with @gambhiro . Just one /usr path is useful to look for the system-wide installed palette and could be chosen at build time, but I suppose it would make the build a little more complex.

The 3 Q*Path() give more choices for the users, with those they can build and use fractorium without installing it.

I found both the ~/ dotfile paths to have an uppercase F, that's different from what you wrote since Linux is usually case sensitive. That's the reason why I used the uppercase in the path I suggested for the application data, for consistency, but I would prefer to have everything lowercase.
Those dotfile paths are decided by the application, since you are using ~/.config/Fractorium there's really no need to search in ~/.Fractorium.

If you want to keep it simple you could just use ~/.config/Fractorium and put last.flame there, without separating configuration files and application data.

I vote to put everything lowercase, for simplicity and to be consistent with the binary name (the first place where a modern Linux user looks for configuration files of a _command_ is in ~/.config/_command_ ).

**Comment by mfeemster** [comment] 2016-03-09 04:39
I've committed a fix that I believe is a middle ground. I believe the uppercase comes from somewhere within Qt I believe and I don't feel like tracking it down so I just left it.

last.flame is saved in ~/.config/Fractorium
I've removed ~/.Fractorium since it's non-standard

Please verify this works.

**Comment by gambhiro** [comment] 2016-03-09 12:52
Thank you! I confirmed it works:

- removed fractorium
- build a local .deb and installed it
- opened fractorium and closed it

```
$ ls -l /usr/share/fractorium/
total 1540
-rw-r--r-- 1 root root   11422 Mar  9 12:29 dark.qss
-rw-r--r-- 1 root root 1496739 Mar  9 12:29 flam3-palettes.xml
-rw-r--r-- 1 root root   65364 Mar  9 12:29 Fractorium.png

$ ls -l ~/.config/fractorium
total 64
-rw------- 1 yume yume 60216 Mar  9 12:45 fractorium.ini
-rw-rw-r-- 1 yume yume  3682 Mar  9 12:45 last.flame
```

**Comment by mfeemster** [comment] 2016-03-09 14:46
Great, glad all is well.

Also of note, if you open the Style dialog, then open /usr/share/fractorium/dark.qss and click ok, that becomes your new default, which will be saved as ~/.config/fractorium/default.qss and is applied every time you run from then on. Note: if you use dark.qss, see the top few lines to make the tabs look nice in Linux.

Closing this now.

**Closed by mfeemster** 2016-03-09 14:46 UTC
