### ISSUE TITLE
Several Problems with the newest Commit(emberrender bugs)

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#63] opened 2016-02-08 16:30 UTC
Emberrender still complains 
`emberrender: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by emberrender)`
`emberrender: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /usr/lib/libEmberCL.so)`
`emberrender: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /usr/lib/libEmberCL.so)`
at start.
`file /usr/local/cuda/lib64/libOpenCL.so.1` says
`/usr/local/cuda/lib64/libOpenCL.so.1: symbolic link to 'libOpenCL.so'`
so maybe it shouldn't ask a link for information?

Thanks for adding the correct Linux paths, but i guess your ultra hightechy way of obfuscating code with these new lambda, template and what so ever stuff lead to a lill' problem here. (At least i didn't understand shit anymore, so i couldn't fix it, is that really C/C++ what you write there? The last time i seriously coded stuff, was with kilgards glut examples and later the ageia physx sdk, which i understood very well, but this python like crap that comes out of nowhere and references itself in itself and probably also fractalizes itself trough the fourth dimension of its own anus or worse, defies somehow the clarity C languages once had, if these path's would have been written in some good old arrays, with a for loop and some if's and else's according to what has been found on the system, i bet i had no problem to stop it appending everything in the list to one string, but that strange new stuff was quite a too heavy comeback for my rusty brain:|)
--->`emberrender without --flam3_palettes=<val>` craps out with:
`Error parsing palette file flam3-palettes.xml. Reason: `
`Add : Couldn't read palette file flam3-palettes.xml`
`Add : Couldn't read palette file ./~/.fractorium~/.config/fractorium/usr/share/fractorium/usr/local/share/fractorium/flam3-palettes.xml`

**Comment by mfeemster** [comment] 2016-02-08 19:16
Ha, good catch, that's definitely a bug. I'll fix it this week.

**Comment by MAD-OVERLORD** [comment] 2016-02-09 07:48
Since i was closing all the thousands open Stackoverflow tabs till now, which i opened to find myself a solution to that several hours ago, i just wanted to ask as a last question, could you perhaps then do this commit in a way, that it doesn't go under in all the other stuff you do, so that i could better see how you did that, since i studied over an hour  or so, like a slapped monkey how this may be fixed, but this new C++ style prevented that somehow.

Another question i'm asking myself at the moment is, should i learn C++11 when there seem to be already C++14 out there and do they really plan, that one learns all 3 years a almost new language??? 
My poor brain is already totally overlanguaged ,4human ones and first "windoze batch", html, then javascript, then visual basic, then C then probably C++98 or 03, then php, then bash and sometimes even a bit python in blender and now C++14 or 11?

**Comment by mfeemster** [comment] 2016-02-09 23:56
Sure, I've committed a single file with the fix. As you'll see, I missed some commas =)

Please update, build and verify it works, then close this issue.

Sorry for usually having such large commits, but I'm always working on many things.

Further questions about learning/career path are not suitable for here. Feel free to email me about that if you want.

**Comment by MAD-OVERLORD** [comment] 2016-02-11 03:53
Thanks a lot man, now i even feel even more like a slapped monkey, that i didn't found that out myself, this new C++ style was really like a confusing shell game or something, so i was more concentrated on how you parse these paths or even more on how this new stuff even works. 
With the old array assignment i probably would have seen that in the blink of an eye, but since everything was so different in this C++11, i thought that vectors maybe split by newlines now. 

It works the right way now, but i don't close this issue for now, because emberrender still complains about  
`emberrender: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by emberrender)`
`emberrender: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /usr/lib/libEmberCL.so)`
`emberrender: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /usr/lib/libEmberCL.so)`
at start.

As i already mentioned, maybe it has to do something with the fact, that  
`/usr/local/cuda/lib64/libOpenCL.so.1`
 is only a symlink to
` /usr/local/cuda/lib64/libOpenCL.so`
as
`file /usr/local/cuda/lib64/libOpenCL.so.1`
Result:
`/usr/local/cuda/lib64/libOpenCL.so.1: symbolic link to 'libOpenCL.so' `
or
`file /usr/local/cuda/lib64/libOpenCL.so`
Result:
`/usr/local/cuda/lib64/libOpenCL.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, stripped`
would tell you on Linux(Side note, If you ever need to know if a batch of windoze dll's are 64bit or 32bit, `file` command on Linux is your best friend)
So without looking at the code, my problem sniffer assumes emberrender shouldn't seek for informations from a symlink.
Sorry that i don't just fix things, as i mentioned, i will first have to build up a secure development environment and then relearn C++ again, and finally integrating in such a huge project after almost a decade of non C coding would sadly take a while, the fact that i am seriously ill from a deadly sickness called "real" life doesn't make things better, therefore please forgive me, that i am just a good or maybe too good "truffle" pig for bugs at the moment :D

**Comment by mfeemster** [comment] 2016-02-11 03:56
Ok cool, glad the fix was clear.

Regarding the lib stuff, I am not managing the Linux install. @gambhiro , care to take a look at this?

**Comment by gambhiro** [comment] 2016-02-11 21:17
It seems to be just the way the cuda libs are installed. Nothing good occurs to me about how to avoid the warnings from emberrender. Perhaps @MAD-OVERLORD will have a good idea sometime about how to improve it.

**Comment by mfeemster** [comment] 2016-02-11 21:27
@gambhiro Do you get this problem as well on Linux? I don't understand why EmberRender is requiring any type of version information from the OpenCL libs? If we can't solve it, I would at least like to know why it's happening.

**Comment by gambhiro** [comment] 2016-02-11 21:30
No, I haven't encountered these warnings. It is not clear to me how to reproduce them.

**Closed** 2016-03-13 17:27 UTC
